[package]
name = "mcf-config-demo-lib"
version = "0.1.0"
authors = ["James Munns <james@onevariable.com>"]
edition = "2018"

[dependencies]
mcf-config-demo-settings = { path = "../mcf-config-demo-settings" }