[package]
name = "mcf-config-demo-lib"
version = "0.1.0"
authors = ["James Munns <james@onevariable.com>"]
edition = "2018"
description = "A Proof of Concept"
license = "MIT"
repository = "https://github.com/jamesmunns/mcf-config-demo"

[dependencies]
mcf-config-demo-settings = "0.1"