[package]
name = "mcf-config-demo-app"
version = "0.1.0"
authors = ["James Munns <james@onevariable.com>"]
edition = "2018"

[dependencies]
mcf-config-demo-lib = "0.1"

# Uncomment this to modify default behavior
# [patch.crates-io.mcf-config-demo-settings]
# path = "../mcf-config-demo-override"